FROM fedora:37

RUN dnf install -y \
    https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-37.noarch.rpm \
    https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-37.noarch.rpm

RUN dnf install -y \
    ffmpeg \
    ImageMagick \
    perl-Image-ExifTool \
    python3 \
    python3-pip

RUN pip3 install filetype pillow sh

COPY thumbnailer.py /usr/bin/thumbnailer.py
RUN chmod +x /usr/bin/thumbnailer.py

ENTRYPOINT ["/usr/bin/thumbnailer.py"]
